<?php
/*
 * @ https://EasyToYou.eu - IonCube v11 Decoder Online
 * @ PHP 7.2 & 7.3
 * @ Decoder version: 1.0.6
 * @ Release: 10/08/2022
 */

define("THIS_SCRIPT", "play.php");
$rootpath = "./../";
require $rootpath . "global.php";
$lang->load("shoutcast");
define("TS_SHOUTCAST", true);
require "./setup.php";
if ($_GET["type"] == "mp") {
    echo "\r\n\t<html>\r\n\t<head>\r\n\t<title>" . $scdef . " Media Player</title>\r\n\t<link $rel = \"stylesheet\" $href = \"style.css\" $type = \"text/css\">\r\n\t</head>\r\n\t<body $topmargin = \"0\" $leftmargin = \"0\" $rightmargin = \"0\" $bottommargin = \"0\">\r\n\t<table class=\"tborder\" $cellpadding = \"6\" $cellspacing = \"1\" $border = \"0\" $width = \"100%\" $align = \"center\">\r\n\r\n\t\t<tr>\r\n\t\t\t<td class=\"subheader\">\r\n\t\t\t\t<div $align = \"center\">" . $scdef . ": Media Player</div></td>\r\n\t\t</tr>\r\n\r\n\t\t<tr>\r\n\t<td class=\"page\" $align = \"center\" $id = \"radio\">\r\n\t<OBJECT \r\n\t  ID=\"MediaPlayer\"  $classid = \"CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95\" \r\n\t  CODEBASE=\r\n\t   \"http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701\"\r\n\t  $width = 320 $height = 50\r\n\t  $standby = \"Loading Microsoft Windows Media Player components...\" \r\n\t  $type = \"application/x-oleobject\">\r\n\t\t<PARAM NAME=\"FileName\"           VALUE=\"" . $listenlnk . "\">\r\n\t\t<PARAM NAME=\"TransparentAtStart\" Value=\"true\">\r\n\t\t<PARAM NAME=\"AutoStart\"          Value=\"true\">\r\n\t\t<PARAM NAME=\"AnimationatStart\"   Value=\"false\">\r\n\t  <PARAM NAME=\"ShowStatusBar\"      Value=\"true\">\t\r\n\t  <PARAM NAME=\"ShowControls\"       Value=\"true\">\r\n\t\t<PARAM NAME=\"autoSize\" \t\t Value=\"false\">\r\n\t\t<PARAM NAME=\"displaySize\" \t Value=\"0\">\r\n\t\t<Embed $type = \"application/x-mplayer2\"\r\n\t\t  $pluginspage = \"http://www.microsoft.com/Windows/MediaPlayer/\"\r\n\t\t  $src = \"" . $listenlnk . "\"\r\n\t\t  Name=MediaPlayer\r\n\t\t  AutoStart=1\r\n\t\t  Width=320\r\n\t\t  Height=50\r\n\t\t  $transparentAtStart = 0\r\n\t\t  $autostart = 1\r\n\t\t  $animationAtStart = 0\r\n\t\t  ShowStatusBar=1\r\n\t\t  ShowControls=1\r\n\t\t  $autoSize = 0\r\n\t\t  $displaySize = 0></embed>\r\n\t</OBJECT>\r\n\t</td>\r\n\t</tr>\r\n\t</table>\r\n\t</body>\r\n\t</html>";
}
if ($_GET["type"] == "rp") {
    echo "\r\n\t<html>\r\n\t<head>\r\n\t<link $rel = \"stylesheet\" $href = \"style.css\" $type = \"text/css\">\r\n\t<title>" . $scdef . " Real Player</title>\r\n\t</head>\r\n\t<body $topmargin = \"0\" $leftmargin = \"0\" $rightmargin = \"0\" $bottommargin = \"0\">\r\n\t<table class=\"tborder\" $cellpadding = \"6\" $cellspacing = \"1\" $border = \"0\" $width = \"100%\" $align = \"center\">\r\n\t\t<tr>\r\n\t\t\t<td class=\"subheader\">\r\n\t\t\t\t<div $align = \"center\">" . $scdef . ": Real Player</div></td>\r\n\t\t</tr>\r\n\t<tr>\r\n\t<td class=\"page\" $align = \"center\" $id = \"radio\">\r\n\t<OBJECT ID=RVOCX CLASSID=\"clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA\" WIDTH=375 HEIGHT=100>                \r\n\t\t<param $name = \"src\" $value = \"" . $listenlnk . "\">                \r\n\t\t<param $name = \"autostart\" $value = \"-1\">                \r\n\t\t<param $name = \"console\" $value = \"one\">\r\n\t\t\t<param $name = \"controls\" $value = \"all\">                \r\n\t\t<embed $type = \"audio/x-pn-realaudio-plugin\" SRC=\"" . $listenlnk . "\" WIDTH=375 HEIGHT=100 NOJAVA=true AUTOSTART=true CONTROLS=All CONSOLE=one>\r\n\t\t\t</embed>\r\n\t\t</OBJECT>\t\r\n\t</td>\r\n\t</tr>\r\n\t</table>\r\n\t</body>\r\n\t</html>";
}
if ($_GET["type"] == "qt") {
    echo "\r\n\t<html>\r\n\t<head>\r\n\t<link $rel = \"stylesheet\" $href = \"style.css\" $type = \"text/css\">\r\n\t<title>" . $scdef . " Quicktime</title>\r\n\t</head>\r\n\t<body $topmargin = \"0\" $leftmargin = \"0\" $rightmargin = \"0\" $bottommargin = \"0\">\r\n\t<table class=\"tborder\" $cellpadding = \"6\" $cellspacing = \"1\" $border = \"0\" $width = \"100%\" $align = \"center\">\r\n\r\n\t\t<tr>\r\n\t\t\t<td class=\"subheader\">\r\n\t\t\t\t<div $align = \"center\">" . $scdef . ": QuickTime</div></td>\r\n\t\t</tr>\r\n\t<tr>\r\n\r\n\t<td class=\"page\" $align = \"center\" $id = \"radio\">\r\n\t\t<object $classid = \"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\" $width = \"300\" $height = \"30\" $codebase = \"http://www.apple.com/qtactivex/qtplugin.cab\">\r\n\t\t\t  <param $name = \"src\" $value = \"" . $listenamp . "\" />\r\n\t\t\t  <param $name = \"autoplay\" $value = \"true\" />\r\n\t\t\t  <param $name = \"controller\" $value = \"true\" />\r\n\t\t\t  <embed $height = \"30\" $width = \"300\" $src = \"" . $listenamp . "\" $pluginspage = \"http://www.apple.com/quicktime/download/\" $type = \"video/quicktime\" $controller = \"true\" $autoplay = \"true\" />\r\n\t\t</object>\t\r\n\t</td>\r\n\t</tr>\r\n\t</table>\r\n\t</body>\r\n\t</html>";
}

?>